apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: findsecbugs
inputs:
  language:
    required: false 
runs:
  using: composite
  steps:
    - id: run-orchestrator
      name: findsecbugs
      uses: docker://registry.saas-dev.beescloud.com/staging/compliance-findsecbugs:main-0eef2c6b0087350afeeb59c1928b5314d6f276e4
      shell: bash
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{step.internal.id}}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}        
        CONFIG_JSON: '{\"port\":\"5015\",\"metaInfo\":{\"url\":\"NA\",\"username\":\"NA\",\"password\":\"NA\",\"client_secret\":\"NA\",\"toolName\":\"findsecbugs\"},\"orchestratorInfo\":{\"assetType\":\"CODE\",\"assetIdentifier\":\"${{ cloudbees.scm.repositoryUrl }}\",\"profileIdentifier\":\"${{ cloudbees.scm.branch }}\",\"language\":\"${{ inputs.language }}\"},\"metaInformation\":{\"actor\":\"${{ cloudbees.event.head_commit.author.username }}\",\"commit_id\":\"${{ cloudbees.event.head_commit.id }}\",\"tenent_info\":\"NA\",\"scanner_type\":\"SAST\"}}'
      run: |
        set -x
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{step.internal.id}}"
        cd /
        /bin/bash -c "./executables/findsecbugs & while ! nc -z localhost 5015; do sleep 1; done && ./executables/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"


       
        
