apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: findsecbugs
inputs:
  language:
    required: false 
runs:
  using: composite
  steps:
    - id: run-orchestrator
      name: findsecbugs
      uses: docker://public.ecr.aws/l7o7z1g8/actions/findsecbugs-sast-actions:main-a6fc1168672835ecde20aa5bc6ef05451b79ffe8
      shell: bash
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{step.internal.id}}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}        
       
      run: |
        set +x
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{step.internal.id}}"

        # fetch checkedout repo url and branch into assetIdentifier and profileIdentifier
        assetIdentifier=$(git config --get remote.origin.url)
        currentBranch=$(git branch | grep "*")
        profileIdentifier=${currentBranch:2}
        
        CONFIG_JSON='{\"port\":\"5015\",\"metaInfo\":{\"url\":\"NA\",\"username\":\"NA\",\"password\":\"NA\",\"client_secret\":\"NA\",\"toolName\":\"findsecbugs\"},\"orchestratorInfo\":{\"assetType\":\"CODE\",\"assetIdentifier\":\"' 
        CONFIG_JSON+=${assetIdentifier}
        CONFIG_JSON+='\",\"profileIdentifier\":\"'
        CONFIG_JSON+=${profileIdentifier}
        CONFIG_JSON+='\",\"language\":\"${{ inputs.language }}\"},\"metaInformation\":{\"actor\":\"SCM-Bot\",\"commit_id\":\"${{ cloudbees.scm.sha }}\",\"tenent_info\":\"NA\",\"scanner_type\":\"SAST\"}}'

        cd /
        set -x
        /bin/bash -c "./executables/findsecbugs & while ! nc -z localhost 5015; do sleep 1; done && ./executables/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"
